### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by fatmann66** [itsdarklikehell/pwnspeaker#1]
following your directions I believe I installed your plugin.  (found  a type in  one of your scripts) 

received the following in debug. saw no mention of  it (googleapiclient) in the install file:

2020-02-18 00:30:52,467] [DEBUG] loading /root/custom-pi/pwnassistant.py
[2020-02-18 00:30:52,475] [WARNING] error while loading /root/custom-pi/pwnassistant.py: No module named 'googleapiclient'
[2020-02-18 00:30:52,476] [DEBUG] No module named 'googleapiclient'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/__init__.py", line 101, in load_from_path
    load_from_file(filename)
  File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/__init__.py", line 89, in load_from_file
    spec.loader.exec_module(instance)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/custom-pi/pwnassistant.py", line 5, in <module>
    from googleapiclient.discovery import build
ModuleNotFoundError: No module named 'googleapiclient'
[2020-02-18 00:30:52,478] [DEBUG] loading /root/custom-pi/pwnspeaker.py
[2020-02-18 00:30:52,632] [DEBUG] Pwnspeak plugin created
[2020-02-18 00:30:54,692] [DEBUG] loaded plugin pwnspeaker as <pwnspeaker.Pwnspeak object at 0x74dd7ed0>
[2020-02-18 00:30:54,698] [INFO] grid plugin loaded.
[2020-02-18 00:30:54,699] [INFO] webcfg: Plugin loaded.
[2020-02-18 00:30:54,700] [INFO] [webgpsmap]: plugin loaded
[2020-02-18 00:30:54,700] [INFO] Session-stats plugin loaded.
[2020-02-18 00:30:54,701] [INFO] [led] plugin loaded for /sys/class/leds/led0/brightness
[2020-02-18 00:30:54,701] [INFO] memtemp plugin loaded.
[2020-02-18 00:30:54,706] [WARNING] ui.fps is 0, the display will only update for major changes
[2020-02-18 00:30:54,707] [DEBUG] Pwnspeak plugin loaded
[2020-02-18 00:30:54,708] [DEBUG] Setting up UI elements

**Comment by fatmann66** [comment]
right so  you also need to install:
pip3 install --upgrade google-api-python-client

this made it somewhat functional.  1 thing to note. it "said"
" [DEBUG] Waiting for N seconds..."   instead of the actual time
I also had issue loading my AI ( not sure it that's related) as a swapped over to a Pi 3  for check the audio.

can you  clarify if your plugin is only for  a pi 3 / pi 4 that has audio ( I assume so, but wasn't sure if it  interfaced over BT and used the phone's speaker or not.)

anyway. pretty cool plugin :)
